<?php
$amount = isset($_REQUEST['amount']) ? (float)$_REQUEST['amount'] : 0;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment</title>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
</head>

<body>
    <script>
        function initializeRazorpay(amount, name, email, contact) {
            if (!amount || amount <= 0) {
                alert("Invalid payment amount");
                return;
            }

            // AJAX call to create order
            $.ajax({
                url: "https://phpcrud.himanshukashyap.com/rzp/createOrder.php",
                type: "GET",
                data: { amount: amount },
                dataType: "json",
                error: function(xhr, status, error) {
                    alert("Error in AJAX request: " + error);
                },
                success: function(data) {
                    if (data && data.token && data.key) {
                        var options = {
                            "key": data.key,
                            "amount": amount * 100, // Convert to smallest currency unit
                            "currency": "INR",
                            "name": "DigiCoders Technologies",
                            "description": "Test Transaction",
                            "image": "https://phpcrud.himanshukashyap.com/rzp/logo.jpg",
                            "order_id": data.token, // Generated by server
                            "callback_url": "https://eneqd3r9zrjok.x.pipedream.net/",
                            "prefill": {
                                "name": name,
                                "email": email,
                                "contact": contact
                            },
                            "notes": {
                                "address": "DigiCoders Technologies Private Limited, Lucknow, UP"
                            },
                            "theme": {
                                "color": "#3399cc"
                            },
                            "handler": function(response) {
                                alert("Payment Successful! Transaction ID: " + response.razorpay_payment_id);
                                window.location.href = "success.php";
                            }
                        };

                        // Initialize Razorpay
                        var rzp1 = new Razorpay(options);

                        // Open Razorpay
                        rzp1.open();

                        // Payment failed callback
                        rzp1.on('payment.failed', function(response) {
                            alert("Payment Failed. Reason: " + response.error.description);
                            window.location.href = "failed.php";
                        });
                    } else {
                        alert("Failed to initialize Razorpay order. Please try again.");
                    }
                }
            });
        }

        // Trigger the function on page load
        window.onload = function() {
            var amount = '<?= htmlspecialchars($amount, ENT_QUOTES) ?>';
            var name = 'Test'; // Replace with dynamic data if available
            var email = 'test@gmail.com'; // Replace with dynamic data if available
            var contact = '999999999'; // Replace with dynamic data if available

            if (amount && name && email && contact) {
                initializeRazorpay(amount, name, email, contact);
            } else {
                alert("Required parameters missing. Please check your input.");
            }
        };
    </script>
</body>

</html>
